language: java
jdk:
- oraclejdk8
script: mvn clean install -Dmaven.test.skip=true

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/ElasticSearch
