language: java
jdk:
- oraclejdk8
sudo: true

install:
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script: mvn clean install

after_success:
- mvn clean cobertura:cobertura coveralls:report

after_script:
  - docker-compose down

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/ElasticSearch
