language: java
jdk:
- oraclejdk8
sudo: true
script: mvn clean install

after_success:
- mvn clean cobertura:cobertura coveralls:report

deploy:
  provider: releases
  skip_cleanup: true

  on:
    tags: true
    all_branches: true
    repo: hakdogan/ElasticSearch
